Repository E3SM-Project/scorpio, pull requests merged in 2018-04, with the labels that each got.

#91 Only use bget for caching user data
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_file.c
Labels: bug

#90 Set PIO buffer cache limit and cleanup bget
  src/clib/bget.c
  src/clib/bget.h
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  tests/general/pio_buf_lim_tests.F90.in
Labels: enhancement

#96 Limit the number of non-contiguous regions in an IO process
  CMakeLists.txt
  src/clib/config.h.in
  src/clib/pio_darray.c
Labels: High Priority, enhancement
