Repository E3SM-Project/scorpio, pull requests merged in 2018-06, with the labels that each got.

#101 Fortran support for async I/O as a service
  src/clib/pio.h
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_internal.h
  src/clib/pio_lists.c
  src/clib/pio_msg.c
  src/clib/pio_nc.c
  src/clib/pio_nc4.c
  src/clib/pio_rearrange.c
  src/clib/pioc.c
  src/clib/pioc_support.c
  src/flib/piolib_mod.F90
  tests/cunit/test_pioc.c
  tests/general/CMakeLists.txt
  tests/general/pio_async_decomp_tests.F90.in
  tests/general/pio_async_decomp_tests_1d.F90.in
  tests/general/pio_async_file_tests.F90.in
  tests/general/pio_async_init_finalize.F90.in
Labels: High Priority, enhancement

#109 Reduce pio_swapm calls in box_rearrange_create
  src/clib/pio_rearrange.c
Labels: Perf, enhancement

#111 Add data type conversions support for ADIOS IO type
  src/clib/pio_darray.c
Labels: bug

#112 Optimize the box rearrange create algorithm
  src/clib/pio_rearrange.c
Labels: High Priority, Perf, enhancement
