Repository E3SM-Project/scorpio, pull requests merged in 2019-11, with the labels that each got.

#260 Add a new Fortran unit test for PIO_initdecomp_bc
  tests/general/pio_decomp_tests_1d.F90.in
Labels: enhancement

#261 Fix two bugs related to PIO_initdecomp_bc overload
  src/clib/pioc.c
  src/flib/piolib_mod.F90
Labels: bug

#263 Check and process the return code from the flush_output_buffer() function
  src/clib/pio_darray.c
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_varm.c
Labels: bug, enhancement

#264 Add PnetCDF block wait support
  src/clib/pio.h
  src/clib/pio_darray_int.c
  src/clib/pio_getput_int.c
  src/clib/pio_internal.h
  tests/cunit/CMakeLists.txt
  tests/cunit/test_req_block_wait.c
Labels: High Priority, Next Release, enhancement
