Repository E3SM-Project/scorpio, pull requests merged in 2019-06, with the labels that each got.

#207 Adding min version checks and removing CMake fortran utils repo
  CMakeLists.txt
  cmake/FindNetCDF.cmake
  cmake/FindPnetCDF.cmake
  cmake/TryCSizeOf.f90
  cmake/TryMPIIO.f90
  cmake/TryMPIMod.f90
  examples/c/CMakeLists.txt
  src/clib/CMakeLists.txt
  src/flib/CMakeLists.txt
  tools/CMakeLists.txt
  tools/adios2pio-nm/CMakeLists.txt
Labels: Next Release, enhancement

#213 Update the condition used to retry opening a file
  src/clib/pioc_support.c
Labels: High Priority, Next Release, bug

#212 Fix BGET usage
  src/clib/bget.c
  src/clib/bget.h
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_internal.h
  src/clib/pioc.c
Labels: High Priority, Next Release, bug, enhancement

#216 Adding support for the Cray compiler
  src/clib/CMakeLists.txt
  tests/cunit/CMakeLists.txt
Labels: High Priority, Next Release, enhancement

#219 Fix c99 flag for PGI
  src/clib/CMakeLists.txt
  tests/cunit/CMakeLists.txt
Labels: High Priority, Next Release, bug

#217 Adding support for compy
  cmake/LibMPI.cmake
  cmake/mpiexec.compy
Labels: High Priority, Next Release, enhancement

#220 Temp fix for XL internal compiler error
  src/clib/CMakeLists.txt
Labels: High Priority, Next Release
