Repository E3SM-Project/scorpio, pull requests merged in 2019-08, with the labels that each got.

#239 Fix XL build issues
  examples/adios/CMakeLists.txt
  examples/c/CMakeLists.txt
  examples/f03/CMakeLists.txt
  tests/general/CMakeLists.txt
  tests/performance/CMakeLists.txt
  tests/unit/CMakeLists.txt
  tools/adios2pio-nm/CMakeLists.txt
Labels: ADIOS, High Priority, Next Release, bug

#241 Explicitly set CMake variable CTEST_CUSTOM_MAXIMUM_NUMBER_OF_WARNINGS
  CTestConfig.cmake
Labels: enhancement

#240 Fix warnings in the code
  examples/adios/timesteps.c
  examples/adios/timesteps_double.c
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_lists.c
  src/clib/pio_msg.c
  src/clib/pio_nc.c
  src/clib/pio_nc4.c
  src/clib/pio_rearrange.c
  src/clib/pio_sdecomps_regex.cpp
  src/clib/pioc.c
  src/clib/pioc_support.c
  src/flib/pio_nf.F90
  src/flib/pio_support.F90
  src/flib/piodarray.F90.in
  src/flib/piolib_mod.F90
  src/flib/pionfatt_mod.F90.in
  src/flib/pionfput_mod.F90.in
  src/gptl/gptl.c
  src/gptl/perf_mod.F90
  src/gptl/perf_utils.F90
  tests/general/ncdf_get_put.F90.in
  tests/general/ncdf_inq.F90.in
  tests/general/pio_async_decomp_tests.F90.in
  tests/general/pio_async_decomp_tests_1d.F90.in
  tests/general/pio_async_file_tests.F90.in
  tests/general/pio_buf_lim_tests.F90.in
  tests/general/pio_decomp_extra_dims.F90.in
  tests/general/pio_decomp_fillval.F90.in
  tests/general/pio_decomp_fillval2.F90.in
  tests/general/pio_decomp_frame_tests.F90.in
  tests/general/pio_decomp_tests.F90.in
  tests/general/pio_decomp_tests2_1d.F90.in
  tests/general/pio_decomp_tests_1d.F90.in
  tests/general/pio_decomp_tests_2d.F90.in
  tests/general/pio_decomp_tests_3d.F90.in
  tests/general/pio_iodesc_tests.F90.in
  tests/general/pio_iosystem_tests.F90.in
  tests/general/pio_iosystem_tests2.F90.in
  tests/general/pio_iosystem_tests3.F90.in
  tests/general/pio_rearr.F90.in
  tests/general/pio_rearr_opts.F90.in
  tests/general/pio_rearr_opts2.F90.in
  tests/general/pio_sync_tests.F90.in
  tests/general/util/pio_tutil.F90
  tests/performance/pioperformance.F90
  tests/performance/pioperformance_rearr.F90
  tests/unit/basic_tests.F90
  tests/unit/driver.F90
  tests/unit/ncdf_tests.F90
Labels: High Priority, Next Release

#242 Add CTest environment variables for anlworkstation
  ctest/CTestEnvironment-anlworkstation.cmake
Labels: enhancement

#235 Adding a separate thread for some ADIOS operations
  src/clib/pioc_support.c
Labels: ADIOS, Next Release, Perf, enhancement

#246 Changing proj name and version
  CMakeLists.txt
  README.md
Labels: Low Priority, Next Release

#254 Avoid assigning character fillvalue to integer
  src/flib/pio_types.F90
Labels: High Priority, Next Release, bug
