Repository E3SM-Project/scorpio, pull requests merged in 2019-12, with the labels that each got.

#265 Fix NetCDF-only build failures and error handling during write
  src/clib/pio.h
  src/clib/pio_darray_int.c
Labels: High Priority, Next Release, bug, enhancement

#268 Fix error handling for serial I/O and reads
  src/clib/pio_darray_int.c
Labels: High Priority, Next Release, bug

#271 Expose preprocessor definitions required by pio.h via pio_config.h
  CMakeLists.txt
  src/clib/CMakeLists.txt
  src/clib/bget.c
  src/clib/pio.h
  src/clib/pio_config.h.in
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_file.c
  src/clib/pio_get_nc.c
  src/clib/pio_getput_int.c
  src/clib/pio_lists.c
  src/clib/pio_mpi_timer.c
  src/clib/pio_msg.c
  src/clib/pio_nc.c
  src/clib/pio_nc4.c
  src/clib/pio_print.c
  src/clib/pio_put_nc.c
  src/clib/pio_rearrange.c
  src/clib/pio_sdecomps_regex.cpp
  src/clib/pio_sdecomps_regex.hpp
  src/clib/pio_spmd.c
  src/clib/pio_timer.c
  src/clib/pio_timer.h
  src/clib/pio_varm.c
  src/clib/pioc.c
  src/clib/pioc_sc.c
  src/clib/pioc_support.c
Labels: High Priority, enhancement

#272 Fix a build error for tools/adios2pio-nm
  tools/adios2pio-nm/CMakeLists.txt
Labels: ADIOS, bug
