Repository E3SM-Project/scorpio, pull requests merged in 2019-02, with the labels that each got.

#161 Switching from ready isends to regular isends
  src/clib/pio_spmd.c
Labels: High Priority, enhancement

#157 Return soft failures in most PIO inquire functions
  src/clib/pio_nc.c
Labels: High Priority

#148 Performance Enhancement for PnetCDF IO type
  src/clib/pio.h
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_lists.c
  src/clib/pioc_support.c
  tests/cunit/test_pioc.c
Labels: High Priority, Perf, enhancement

#162 Merge adios_support to master
  CMakeLists.txt
  cmake/FindADIOS.cmake
  ctest/CTestEnvironment-anlworkstation.cmake
  ctest/CTestScript-Test.cmake
  examples/CMakeLists.txt
  examples/adios/CMakeLists.txt
  examples/adios/README
  examples/adios/example3.c
  examples/adios/examplePioADIOS.f90
  examples/adios/example_num_frames.c
  examples/adios/timesteps.c
  examples/adios/timesteps_double.c
  examples/c/CMakeLists.txt
  examples/c/example1.c
  examples/c/put_var.c
  src/clib/CMakeLists.txt
  src/clib/pio.h
  src/clib/pio_darray.c
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_nc.c
  src/clib/pio_sdecomps_regex.cpp
  src/clib/pioc.c
  src/clib/pioc_support.c
  src/flib/pio.F90
  src/flib/pio_types.F90
  tests/cunit/test_sdecomp_regex.cpp
  tests/general/CMakeLists.txt
  tests/general/ncdf_get_put.F90.in
  tests/general/util/pio_tutil.F90
  tools/CMakeLists.txt
  tools/adios2pio-nm/CMakeLists.txt
  tools/adios2pio-nm/adios2pio-nm-lib-c.h
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
  tools/adios2pio-nm/adios2pio-nm-lib.h
  tools/adios2pio-nm/adios2pio-nm.cxx
Labels: enhancement
