Repository E3SM-Project/scorpio, pull requests merged in 2020-04, with the labels that each got.

#283 Merge adios2_integration to master
  CMakeLists.txt
  cmake/FindADIOS.cmake
  ctest/CTestEnvironment-anlworkstation.cmake
  examples/adios/example3.c
  examples/adios/example_num_frames.c
  examples/c/example1.c
  examples/c/put_var.c
  src/clib/CMakeLists.txt
  src/clib/pio.h
  src/clib/pio_darray.c
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_nc.c
  src/clib/pio_sdecomps_regex.cpp
  src/clib/pioc.c
  src/clib/pioc_support.c
  tests/cunit/test_sdecomp_regex.cpp
  tests/general/pio_iosystem_tests.F90.in
  tests/general/util/pio_tutil.F90
  tools/CMakeLists.txt
  tools/adios2pio-nm/CMakeLists.txt
  tools/adios2pio-nm/adios2pio-nm-lib-c.h
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
  tools/adios2pio-nm/adios2pio-nm-lib.h
  tools/adios2pio-nm/adios2pio-nm.cxx
Labels: ADIOS, Next Release, enhancement

#297 Disable ROMIO hint romio_no_indep_rw for lower versions of MPICH
  src/clib/pioc_support.c
Labels: High Priority, Next Release, bug

#296 Exclude MPI C++ headers
  src/clib/pio_sdecomps_regex.cpp
  tests/cunit/test_sdecomp_regex.cpp
  tools/adios2pio-nm/CMakeLists.txt
  tools/spio_finfo/CMakeLists.txt
Labels: ADIOS, Low Priority, Next Release

#299 Enable ROMIO hint romio_no_indep_rw for Cray MPICH and Intel MPI
  src/clib/pioc_support.c
Labels: High Priority, Next Release

#298 Turn off compression for scalar variables
  src/clib/pio_nc.c
  src/clib/pioc_support.c
Labels: High Priority, Next Release, bug

#300 Use MPI_Isends instead of MPI_Irsends
  pio/CMakeLists.txt
Labels: High Priority, Next Release

#301 Explicitly disable MPI_Irsends
  src/clib/CMakeLists.txt
Labels: High Priority, Next Release
