Repository E3SM-Project/scorpio, pull requests merged in 2020-12, with the labels that each got.

#368 Fix a performance issue for the ADIOS conversion tool
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
Labels: ADIOS, Perf, enhancement

#370 Adding ADIOS to github README
  README.md
Labels: ADIOS

#369 Fix truncation while reading strings with spaces
  src/flib/pionfput_mod.F90.in
  tests/general/ncdf_get_put.F90.in
Labels: High Priority, Next Release, bug

#372 Minor code optimizations to the conversion tool
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
Labels: ADIOS, Perf, enhancement

#374 Remove asserts for non-NULL starts/counts/strides for scalars
  src/clib/pio_getput_int.c
Labels: High Priority, Next Release
