Repository E3SM-Project/scorpio, pull requests merged in 2020-10, with the labels that each got.

#351 Stop GPTL timers on error
  src/clib/gptl_skel.h
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_internal.h
  src/clib/pio_nc.c
  src/clib/pio_nc4.c
  src/clib/pio_rearrange.c
  src/clib/pio_spmd.c
  src/clib/pioc.c
  src/clib/pioc_support.c
  src/gptl/CMakeLists.txt
  src/gptl/gptl.c
  tests/general/ncdf_fail.F90.in
Labels: High Priority, Next Release

#343 Use SCORPIO_SOURCE_DIR instead of CMAKE_SOURCE_DIR
  CMakeLists.txt
  cmake/LibMPI.cmake
  doc/Doxyfile.in
  examples/adios/CMakeLists.txt
  examples/c/CMakeLists.txt
  src/flib/CMakeLists.txt
  tests/cunit/CMakeLists.txt
  tests/unit/CMakeLists.txt
  tools/adios2pio-nm/CMakeLists.txt
  tools/spio_finfo/CMakeLists.txt
Labels: Next Release, enhancement

#353 Fix IBM XL compiler errors on some multiline prints
  src/flib/pionfput_mod.F90.in
Labels: High Priority, Next Release, bug

#355 Remove ncdf_fail nightly tests for ADIOS type
  ctest/CTestScript-Test.cmake
Labels: ADIOS

#360 Adjust the linking order for the ADIOS conversion tool
  tools/adios2pio-nm/CMakeLists.txt
Labels: ADIOS, High Priority, Next Release

#361 Build scorpio tools for nightly tests
  CTestScript.cmake
Labels: ADIOS, Next Release, enhancement

#358 Disable using regex for IBM and PGI compilers
  CMakeLists.txt
  src/clib/pio_sdecomps_regex.cpp
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
  tools/adios2pio-nm/adios2pio-nm.cxx
  tools/spio_finfo/spio_finfo_tool.cxx
  tools/util/argparser.cxx
  tools/util/argparser.h
Labels: ADIOS, High Priority, Next Release

#362 Add a new ADIOS timer to PIOc_put_vars_tc()
  src/clib/pio_getput_int.c
Labels: ADIOS, Next Release, Perf, enhancement

#364 Handle multi-dimensional temporal variables for ADIOS type
  CMakeLists.txt
  src/clib/pio.h
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_nc.c
  tests/general/ncdf_get_put.F90.in
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
Labels: ADIOS, High Priority, Next Release, bug, enhancement
