Repository E3SM-Project/scorpio, pull requests merged in 2020-09, with the labels that each got.

#333 Simplify create_mpi_datatypes() by removing local lindex array
  src/clib/pio_rearrange.c
Labels: Perf, enhancement

#337 Explicit conversion of C strings to Fortran strings during gets
  src/flib/pio_support.F90
  src/flib/pionfget_mod.F90.in
  src/flib/pionfput_mod.F90.in
  tests/general/ncdf_get_put.F90.in
  tests/general/util/pio_tutil.F90
Labels: Next Release, bug

#339 Support text variables written out using Scorpio in Scorpio classic
  pio/pionfget_mod.F90.in
Labels: Next Release, enhancement

#338 Cleanup warnings
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_nc.c
  src/clib/pio_sdecomps_regex.cpp
  src/clib/pioc_support.c
Labels: Next Release

#341 Reduce memory usage on some IO tasks
  src/clib/pio_darray.c
Labels: Next Release, Perf, enhancement

#347 Increase the default pio_buffer_size_limit
  src/clib/pio_darray.c
  tests/cunit/test_iosystem2_simple.c
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
Labels: ADIOS, Next Release, enhancement

#349 Stop timer when get att fails
  src/clib/pio_getput_int.c
Labels: High Priority, Next Release
