Repository E3SM-Project/scorpio, pull requests merged in 2020-01, with the labels that each got.

#275 Fix fortran NetCDF lib detection
  src/flib/CMakeLists.txt
Labels: High Priority, Next Release, bug

#279 Adding a CTest environment variable for anlworkstation
  ctest/CTestEnvironment-anlworkstation.cmake
Labels: High Priority

#277 Improve user messages when retrying with NetCDF
  src/clib/pioc_support.c
Labels: High Priority, Next Release

#276 Scorpio file info tool
  tools/CMakeLists.txt
  tools/adios2pio-nm/CMakeLists.txt
  tools/adios2pio-nm/adios2pio-nm.cxx
  tools/adios2pio-nm/argparser.cxx
  tools/adios2pio-nm/argparser.h
  tools/spio_finfo/CMakeLists.txt
  tools/spio_finfo/spio_file_test_utils.cxx
  tools/spio_finfo/spio_file_test_utils.h
  tools/spio_finfo/spio_finfo.cxx
  tools/spio_finfo/spio_finfo.h
  tools/spio_finfo/spio_finfo_tool.cxx
  tools/util/argparser.cxx
  tools/util/argparser.h
  tools/util/spio_lib_info.cxx
  tools/util/spio_lib_info.h
  tools/util/spio_misc_tool_utils.cxx
  tools/util/spio_misc_tool_utils.h
Labels: High Priority, Next Release, enhancement

#278 Adding fixes required for standalone HOMME
  CMakeLists.txt
  src/clib/CMakeLists.txt
  src/clib/pio.h
  src/clib/pio_internal.h
  src/clib/pio_msg.c
  src/clib/pio_nc.c
  src/flib/CMakeLists.txt
  src/flib/pio.F90
  src/flib/pio_nf.F90
  src/flib/pio_nf_utils.F90
  src/gptl/CMakeLists.txt
  tests/general/CMakeLists.txt
  tests/general/pio_async_copy_tests.F90.in
  tests/general/pio_copy.F90.in
  tools/adios2pio-nm/CMakeLists.txt
Labels: High Priority, Next Release, enhancement

#281 Fix sync issue with deleting files in async copy test
  src/clib/pio_internal.h
  src/clib/pio_print.c
  tests/general/pio_async_copy_tests.F90.in
Labels: High Priority, Next Release, bug
