Repository E3SM-Project/scorpio, pull requests merged in 2021-03, with the labels that each got.

#321 Fix and simplify CalcStartandCount() for BOX rearranger
  src/clib/pioc_sc.c
  tests/cunit/test_spmd.c
Labels: High Priority, Next Release, Perf, bug, enhancement

#390 Adding I/O performance statistics
  CMakeLists.txt
  src/clib/CMakeLists.txt
  src/clib/io_perf_summary.json_expected
  src/clib/io_perf_summary.schema.json
  src/clib/io_perf_summary.text_expected
  src/clib/io_perf_summary.xml_expected
  src/clib/pio.h
  src/clib/pio_config.h.in
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_internal.h
  src/clib/pio_lists.c
  src/clib/pio_nc.c
  src/clib/pio_nc4.c
  src/clib/pio_varm.c
  src/clib/pioc.c
  src/clib/pioc_support.c
  src/clib/spio_io_summary.cpp
  src/clib/spio_io_summary.h
  src/clib/spio_io_summary.hpp
  src/clib/spio_ltimer.cpp
  src/clib/spio_ltimer.h
  src/clib/spio_ltimer.hpp
  src/clib/spio_serializer.cpp
  src/clib/spio_serializer.hpp
  src/clib/spio_tree.hpp
  tests/cunit/CMakeLists.txt
  tests/cunit/test_spio_ltimer.cpp
  tests/cunit/test_spio_serializer.cpp
  tests/cunit/test_spio_tree.cpp
Labels: High Priority, Next Release, enhancement

#392 Support I/O performance statistics collection with the MPI serial library
  src/clib/spio_io_summary.cpp
Labels: High Priority, Next Release, bug

#397 Adding <sstream> for stringstream
  tools/util/argparser.cxx
Labels: High Priority, Next Release, bug

#395 Adding XML serializer and fixing remaining issues in the serializer
  src/clib/io_perf_summary.schema.json
  src/clib/spio_serializer.cpp
  src/clib/spio_serializer.hpp
  src/clib/spio_tree.hpp
  tests/cunit/test_spio_serializer.cpp
Labels: High Priority, Next Release, enhancement

#391 Put user-provided paths first in the list of search dirs in LibFind
  cmake/LibFind.cmake
Labels: High Priority, Next Release, enhancement

#399 Miscellaneous bug fixes and enhancements for SCORPIO's performance replay tool
  tests/performance/pioperformance_rearr.F90
Labels: ADIOS, Perf, bug, enhancement

#404 Support I/O performance summary for ADIOS type
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_getput_int.c
  src/clib/pioc.c
  src/clib/pioc_support.c
  src/clib/spio_io_summary.cpp
  src/clib/spio_io_summary.h
Labels: ADIOS, Next Release, enhancement
