Repository E3SM-Project/scorpio, pull requests merged in 2021-06, with the labels that each got.

#413 Fix issues with setting hints
  src/flib/CMakeLists.txt
  src/flib/pio_support.F90.in
  src/flib/piolib_mod.F90
  src/flib/pionfput_mod.F90.in
  tests/general/CMakeLists.txt
  tests/general/pio_set_hint.F90.in
Labels: High Priority, Next Release, bug

#412 Set default striping factor and unit hints for Lustre and GPFS file systems
  CMakeLists.txt
  src/clib/pio_config.h.in
  src/clib/pioc_support.c
Labels: Perf, enhancement

#415 Conditionally initialize/finalize GPTL in the pioperf_rearr tool
  tests/performance/pioperformance_rearr.F90
Labels: bug
