Repository E3SM-Project/scorpio, pull requests merged in 2021-01, with the labels that each got.

#381 Adding new interface for async I/O
  pio/piolib_mod.F90
Labels: High Priority, Next Release, enhancement

#379 Optimize the ADIOS conversion tool
  src/clib/pio.h
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_nc.c
  tools/adios2pio-nm/adios2pio-nm-lib-c.h
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
  tools/adios2pio-nm/adios2pio-nm-lib.h
  tools/adios2pio-nm/adios2pio-nm.cxx
Labels: ADIOS, Next Release, Perf, enhancement

#382 Adding support for Chrysalis
  cmake/LibMPI.cmake
Labels: High Priority, Next Release, enhancement

#380 Adding new async I/O interface
  src/flib/piolib_mod.F90
  tests/general/pio_async_init_finalize.F90.in
Labels: High Priority, Next Release, enhancement

#384 Signal pio_unit_test as failed when a Fortran function returns an error
  tests/unit/basic_tests.F90
Labels: enhancement
