Repository E3SM-Project/scorpio, pull requests merged in 2022-12, with the labels that each got.

#498 Fix cray+rocm build issues
  src/clib/CMakeLists.txt
  src/clib/bget.h
  src/clib/pio.h
  src/clib/pio_internal.h
  src/clib/pio_mpi_timer.c
  src/clib/pio_sdecomps_regex.cpp
  src/clib/pio_sdecomps_regex.h
  src/clib/pio_sdecomps_regex.hpp
  src/clib/pio_timer.h
  src/clib/spio_file_mvcache.cpp
  src/clib/spio_file_mvcache.h
  src/clib/spio_file_mvcache.hpp
  src/clib/spio_io_summary.cpp
  src/clib/spio_io_summary.h
  src/clib/spio_ltimer.cpp
  src/clib/spio_ltimer.h
  src/gptl/CMakeLists.txt
  src/gptl/private.h
  tests/cunit/pio_tests.h
  tests/cunit/test_sdecomp_regex.cpp
  tests/cunit/test_spio_file_mvcache.cpp
  tests/cunit/test_spio_ltimer.cpp
  tests/cunit/test_spio_serializer.cpp
  tests/cunit/test_spio_tree.cpp
  tools/adios2pio-nm/adios2pio-nm-lib-c.h
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
  tools/adios2pio-nm/adios2pio-nm-lib.h
  tools/spio_finfo/spio_file_test_utils.h
  tools/spio_finfo/spio_finfo.h
  tools/util/argparser.h
  tools/util/spio_lib_info.h
  tools/util/spio_misc_tool_utils.h
Labels: Next Release

#500 Fix missing flush function with XL
  src/gptl/CMakeLists.txt
Labels: High Priority, Next Release

#502 Set NC_NODIMSCALE_ATTACH flag to create files with NETCDF4P type
  src/clib/pioc_support.c
Labels: enhancement, High Priority, Next Release
