Repository E3SM-Project/scorpio, pull requests merged in 2022-10, with the labels that each got.

#486 HDF5 IO type integration
  CMakeLists.txt
  ctest/CTestEnvironment-anlgce.cmake
  ctest/CTestScript-Test.cmake
  examples/c/CMakeLists.txt
  examples/c/test_hdf5.c
  src/clib/CMakeLists.txt
  src/clib/pio.h
  src/clib/pio_config.h.in
  src/clib/pio_darray.c
  src/clib/pio_darray_int.c
  src/clib/pio_file.c
  src/clib/pio_getput_int.c
  src/clib/pio_nc.c
  src/clib/pioc.c
  src/clib/pioc_support.c
  src/flib/pio.F90
  src/flib/pio_types.F90
  tests/general/util/pio_tutil.F90
  tests/performance/pioperformance_rearr.F90
Labels: enhancement, High Priority, Perf

#487 Reserve some extra space in the header only once when creating NetCDF files
  CMakeLists.txt
  src/clib/pio.h
  src/clib/pio_config.h.in
  src/clib/pioc_support.c
Labels: enhancement, High Priority, Perf, Next Release, bugfix

#488 Set default Lustre striping factor and unit for Perlmutter
  CMakeLists.txt
Labels: enhancement, Perf, Next Release

#491 Add declaration of function used to write I/O summary
  src/clib/pio_lists.c
Labels: High Priority, Next Release, bugfix
