Repository E3SM-Project/scorpio, pull requests merged in 2024-04, with the labels that each got.

#578 Support for PIO_REARR_ANY in Fortran legacy interface
  src/flib_legacy/pio.F90
  src/flib_legacy/pio_types.F90
Labels: enhancement, High Priority, Next Release

#580 Specify the POSIX standard required for the C library
  src/clib/CMakeLists.txt
Labels: High Priority, Next Release

#581 Fix PIO_USE_INDEP_MODE cmake option
  CMakeLists.txt
Labels: Next Release

#582 Bug fixes and enhancements for ADIOS IO type to handle attributes
  examples/c/test_adios.c
  src/clib/pio_getput_int.c
  src/clib/pioc_support.c
Labels: enhancement, Next Release, ADIOS, bugfix
