Repository E3SM-Project/scorpio, pull requests merged in 2024-07, with the labels that each got.

#593 Perform full matching of decomposition maps for ADIOS read
  src/clib/pio_darray.cpp
Labels: enhancement, High Priority, Next Release, ADIOS, bugfix

#592 Perform full matching of decomposition maps for ADIOS read
  src/clib/pio_darray.c
Labels: enhancement, High Priority, Next Release, ADIOS, bugfix

#597 Optionally exclude decomposition data from ADIOS BP files
  CMakeLists.txt
  ctest/CTestEnvironment-anlgce.cmake
  ctest/CTestScript-Test.cmake
  src/clib/CMakeLists.txt
  src/clib/pio.h
  src/clib/pio_darray.cpp
  src/clib/pioc_support.cpp
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
Labels: enhancement, Next Release, ADIOS

#601 Adding dummy support for pio_rearr_any in v1.4.*
  src/clib/pio.h
  src/flib/pio.F90
  src/flib/pio_types.F90
Labels: enhancement

#600 Fix issues with the C++ cray compiler
  src/clib/pio_getput_int.cpp
  tests/general/pio_set_hint.F90.in
Labels: bug, Next Release

#585 Fix usage of find_package_handle_standard_args
  cmake/FindGPTL.cmake
  cmake/FindHDF5.cmake
  cmake/FindMPE.cmake
  cmake/FindMPISERIAL.cmake
  cmake/FindNetCDF.cmake
  cmake/FindPnetCDF.cmake
  cmake/LibFind.cmake
Labels: Next Release, cmake
