Repository E3SM-Project/scorpio, pull requests merged in 2024-02, with the labels that each got.

#563 Optimize PIOc_read_darray_adios() with efficient block guessing
  src/clib/pio_darray.c
Labels: enhancement, High Priority, Perf, Next Release, ADIOS

#560 Adding a CMake package for SCORPIO
  CMakeLists.txt
  cmake/FindHDF5.cmake
  cmake/SPIOUtils.cmake
  cmake/scorpio-config.cmake.in
  examples/adios/CMakeLists.txt
  examples/adios/example3.c
  examples/adios/example_num_frames.c
  examples/adios/timesteps.c
  examples/adios/timesteps_double.c
  examples/basic/CMakeLists.txt
  examples/basic/testpio.F90
  examples/c/CMakeLists.txt
  examples/c/darray_async.c
  examples/c/darray_no_async.c
  examples/c/example1.c
  examples/c/example2.c
  examples/c/examplePio.c
  examples/c/put_var.c
  examples/c/test_adios.c
  examples/c/test_hdf5.c
  examples/cxx/CMakeLists.txt
  examples/f03/CMakeLists.txt
  src/clib/CMakeLists.txt
  src/clib/pio_internal.h
  src/flib/CMakeLists.txt
  src/flib_legacy/CMakeLists.txt
  src/gptl/CMakeLists.txt
  tests/cunit/CMakeLists.txt
  tests/cunit/test_common.c
  tests/cunit/test_req_block_wait.c
  tests/cunit/test_sdecomp_regex.cpp
  tests/cunit/test_spio_file_mvcache.cpp
  tests/cunit/test_spio_ltimer.cpp
  tests/cunit/test_spio_serializer.cpp
  tests/cunit/test_spio_tree.cpp
  tests/general/CMakeLists.txt
  tests/general/test_memleak.c
  tests/general/util/pio_tutil.F90
  tests/performance/CMakeLists.txt
  tests/performance/pioperformance_rearr.F90
  tests/unit/CMakeLists.txt
  tests/unit/driver.F90
  tools/adios2pio-nm/CMakeLists.txt
  tools/adios2pio-nm/adios2pio-nm.cxx
  tools/spio_finfo/CMakeLists.txt
  tools/spio_finfo/spio_finfo_tool.cxx
Labels: enhancement, High Priority, Next Release

#564 Add symlinks for ADIOS BP output files
  src/clib/pio_file.c
  src/clib/pio_internal.h
  src/clib/pioc_support.c
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
Labels: enhancement, High Priority, Next Release, ADIOS

#565 Remove openfile retry calls from examples
  examples/c/darray_async.c
  examples/c/darray_no_async.c
Labels: High Priority, Next Release, bugfix

#567 Replace ncmpi_enddef() with ncmpi__enddef() to avoid potential hanging issues
  src/clib/pioc_support.c
Labels: enhancement, High Priority, Next Release, bugfix
