Repository E3SM-Project/scorpio, pull requests merged in 2024-11, with the labels that each got.

#615 Enable data compression for ADIOS BP files
  CMakeLists.txt
  ctest/CTestEnvironment-anlgce.cmake
  src/clib/CMakeLists.txt
  src/clib/pio.h
  src/clib/pio_darray.cpp
  src/clib/pio_file.cpp
  src/clib/pio_getput_int.cpp
  src/clib/pio_internal.h
  src/clib/pio_nc.cpp
  src/clib/pioc.cpp
  src/clib/pioc_support.cpp
Labels: enhancement, ADIOS

#617 Adding dummy type PIO_IOTYPE_ADIOSC to maint v1.4
  src/clib/pio.h
  src/flib/pio.F90
  src/flib/pio_types.F90
Labels: High Priority, Next Release

#621 Fix symlink del issues with NetCDF
  src/clib/pio_file.cpp
Labels: bug, ADIOS

#618 Adding PIO_IOTYPE_ADIOSC iotype
  src/clib/pio.h
  src/clib/pio_darray.cpp
  src/clib/pio_file.cpp
  src/clib/pio_getput_int.cpp
  src/clib/pio_nc.cpp
  src/clib/pio_print.cpp
  src/clib/pioc.cpp
  src/clib/pioc_support.cpp
  src/flib/pio.F90
  src/flib/pio_types.F90
  src/flib_legacy/pio.F90
  src/flib_legacy/pio_types.F90
  tests/general/util/pio_tutil.F90
Labels: enhancement, ADIOS

#623 Apply a workaround for CMake FindMPI regression on Cray systems
  CMakeLists.txt
Labels: High Priority, Next Release, cmake
