Repository E3SM-Project/scorpio, pull requests merged in 2024-03, with the labels that each got.

#573 Prevent potential segmentation faults in write_darray_multi_par()
  src/clib/pio_darray_int.c
Labels: High Priority, Next Release, ADIOS, bugfix

#575 Support builds that add source via add_subdirectory
  examples/CMakeLists.txt
  examples/adios/CMakeLists.txt
  examples/basic/CMakeLists.txt
  examples/c/CMakeLists.txt
  examples/cxx/CMakeLists.txt
  examples/f03/CMakeLists.txt
  src/clib/CMakeLists.txt
  src/flib/CMakeLists.txt
  src/flib_legacy/CMakeLists.txt
  tests/cunit/CMakeLists.txt
  tests/general/CMakeLists.txt
  tests/performance/CMakeLists.txt
  tests/unit/CMakeLists.txt
  tools/CMakeLists.txt
  tools/adios2pio-nm/CMakeLists.txt
  tools/spio_finfo/CMakeLists.txt
Labels: High Priority, Next Release, cmake

#577 Adding PIO_REARR_ANY rearranger
  CMakeLists.txt
  src/clib/CMakeLists.txt
  src/clib/pio.h
  src/clib/pio_config.h.in
  src/clib/pioc.c
  src/clib/spio_rearrange_any.cpp
  src/clib/spio_rearrange_any.h
  src/flib/pio.F90
  src/flib/pio_types.F90
  tests/general/pio_rearr.F90.in
Labels: enhancement, High Priority, Next Release
