Repository E3SM-Project/scorpio, pull requests merged in 2025-06, with the labels that each got.

#650 Add workaround to override ADIOS type with PnetCDF for file creation
  CMakeLists.txt
  src/clib/pio_config.h.in
  src/clib/pioc_support.cpp
Labels: enhancement, Next Release, ADIOS

#651 Allow regex for specifying input files to the conversion tool
  tools/adios2pio-nm/README_conversion_tool.txt
  tools/adios2pio-nm/adios2pio-nm-lib.cxx
  tools/adios2pio-nm/adios2pio-nm-lib.h
  tools/adios2pio-nm/adios2pio-nm.cxx
Labels: enhancement, ADIOS

#653 Disable NCZarr by default
  CMakeLists.txt
  src/clib/CMakeLists.txt
Labels: High Priority, Next Release
