Repository E3SM-Project/scorpio, pull requests merged in 2025-02, with the labels that each got.

#630 Enable lossy data compression for ADIOS BP files
  CMakeLists.txt
  ctest/CTestEnvironment-anlgce.cmake
  src/clib/CMakeLists.txt
  src/clib/pio.h
  src/clib/pioc.cpp
  src/clib/pioc_support.cpp
Labels: enhancement, Next Release, ADIOS

#632 Update test_compare_offsets() with additional test cases for 64-bit offset comparisons
  tests/cunit/test_rearr.c
Labels: enhancement

#631 Fix for potential integer under/overflow issue with reading very large files
  src/clib/pio_rearrange.cpp
Labels: bug, Next Release

#633 Fix I/O library version check
  cmake/LibCheck.cmake
  src/clib/CMakeLists.txt
  src/flib/CMakeLists.txt
  tools/CMakeLists.txt
  tools/adios2pio-nm/CMakeLists.txt
  tools/spio_finfo/CMakeLists.txt
Labels: Low Priority, Next Release

#635 Handle ADIOS compression limitations with ZFP
  src/clib/pio_darray.cpp
  src/clib/pio_getput_int.cpp
  src/clib/pioc_support.cpp
Labels: enhancement, Next Release, ADIOS
